//
// Created by bernard on 07/04/2022.
//

#ifndef ONE_COLOR_GL_CONFIGURATION_H
#define ONE_COLOR_GL_CONFIGURATION_H

#define DEFAULT_WIDTH  640
#define DEFAULT_HEIGHT 640

#endif //ONE_COLOR_GL_CONFIGURATION_H
